---
- name: Perform comprehensive health check on Windows servers
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ping the host to check WinRM connectivity
      ansible.windows.win_ping:
      register: ping_result
      ignore_errors: true

    - name: Check for pending Windows updates
      ansible.windows.win_updates:
        state: searched
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
      register: update_check
      ignore_errors: true

    - name: Get CPU usage percentage via PowerShell
      ansible.windows.win_shell: |
        Get-CimInstance -ClassName Win32_PerfFormattedData_PerfOS_Processor | Select-Object -ExpandProperty PercentProcessorTime | Measure-Object -Average
      register: cpu_usage
      changed_when: false

    - name: Get system uptime in days via PowerShell
      ansible.windows.win_shell: |
        $LastBootUpTime = (Get-CimInstance -ClassName Win32_OperatingSystem).LastBootUpTime
        $Uptime = (New-TimeSpan -Start $LastBootUpTime -End (Get-Date)).TotalDays
        Write-Output $Uptime
      register: uptime_days
      changed_when: false

    - name: Get information about critical services
      ansible.windows.win_service_info:
        name: "{{ item }}"
      loop:
        - Spooler
        - Winmgmt
      register: service_info_results

    - name: Check status of critical services
      ansible.builtin.debug:
        msg: "WARNING: Service {{ item.item }} is not running (Current State: {{ item.services[0].state }})"
      loop: "{{ service_info_results.results }}"
      when: item.services[0].state != 'Running'

    - name: Display host and system information
      ansible.builtin.debug:
        msg: |
          --- Health Check Report for {{ ansible_hostname }} ---
          Connectivity Status: {{ 'OK' if not ping_result.failed else 'FAILED' }}
          OS Name: {{ ansible_facts.os_name }}
          OS Version: {{ ansible_facts.os_version }}
          OS Build: {{ ansible_facts.product_build }}
          System Uptime: {{ uptime_days.stdout | round(2) }} days
          Average CPU Usage: {{ cpu_usage.stdout | replace(',', '.') | float | round(2) }}%
          Total Memory: {{ (ansible_facts.memtotal_mb / 1024) | round(2) }} GB
          Free Memory: {{ (ansible_facts.memfree_mb / 1024) | round(2) }} GB

    - name: Display disk space usage and check for low space
      ansible.builtin.debug:
        msg: |
          {% for mount in ansible_facts.mounts %}
          Drive {{ mount.mount }} has {{ (mount.size_available / 1024**3) | round(2) }} GB free of {{ (mount.size_total / 1024**3) | round(2) }} GB total ({{ (mount.size_available / mount.size_total * 100) | round(2) }}% free).
          {% if (mount.size_available / mount.size_total * 100) < 10 %}
          WARNING: Low disk space on {{ mount.mount }}.
          {% endif %}
          {% endfor %}
      when: ansible_facts.mounts | length > 0

    - name: Check status of specific critical services
      ansible.builtin.debug:
        msg: "WARNING: Service {{ item.name }} is not running (Current State: {{ item.state }})"
      loop: "{{ service_info.services }}"
      when: item.state != 'Running'

    - name: Report on pending Windows updates
      ansible.builtin.debug:
        msg: "{{ update_check.updates | length }} updates are pending installation."
      when: update_check.updates is defined and update_check.updates | length > 0

    - name: Report no pending updates found
      ansible.builtin.debug:
        msg: "No pending updates found."
      when: not (update_check.updates is defined and update_check.updates | length > 0)
