---
- name: Check sudo credentials (non-interactive)
  hosts: all
  gather_facts: no
  tasks:
    - name: Whoami as normal user
      command: whoami
      register: whoami_normal

    - name: Whoami with become
      command: whoami
      become: yes
      register: whoami_become
      ignore_errors: yes

    - name: Non-interactive sudo check (no prompt)
      command: sudo -n true
      register: sudo_noninteractive
      ignore_errors: yes

    - name: Simulate apt-get update (no actual changes)
      command: apt-get -s update
      become: yes
      register: apt_sim
      ignore_errors: yes

    - name: Show concise results
      debug:
        msg:
          - "whoami_normal: {{ whoami_normal.stdout }}"
          - "whoami_become: {{ whoami_become.stdout | default('ERROR or same as normal') }}"
          - "sudo -n rc: {{ sudo_noninteractive.rc }} (0 means passwordless sudo allowed)"
          - "apt-sim rc: {{ apt_sim.rc }}"
          - "apt-sim stderr (last 10 lines): {{ (apt_sim.stderr_lines | default([]))[-10:] | default([]) }}"
