---
- hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_result

    - name: Show upgrade summary
      debug:
        msg:
          - "Packages upgraded: {{ upgrade_result.upgraded | default(0) }}"
          - "Packages newly installed: {{ upgrade_result.installed | default(0) }}"
          - "Packages removed: {{ upgrade_result.removed | default(0) }}"
      when: upgrade_result is defined

    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: yes

    - name: Clean up old package archives
      ansible.builtin.apt:
        autoclean: yes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server if required
      ansible.builtin.reboot:
        msg: "Rebooting to apply updates"
        reboot_timeout: 600
      when: reboot_required_file.stat.exists