---
- name: Perform full system update, upgrade, and cleanup
  hosts: all
  become: yes  # Use sudo for all tasks

  pre_tasks:
    - name: Wait for apt lock to be released
      ansible.builtin.command: while pgrep -f 'apt|dpkg'; do sleep 5; done
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Perform full upgrade
      ansible.builtin.apt:
        upgrade: full
      register: upgrade_result

    - name: Remove unused dependencies with autoremove
      ansible.builtin.apt:
        autoremove: yes

    - name: Clean up old package archives
      ansible.builtin.apt:
        autoclean: yes

    - name: Reboot if kernel was updated
      ansible.builtin.reboot:
        msg: "Rebooting to apply kernel updates"
        reboot_timeout: 600
      when: upgrade_result.reboot_required | default(false)
