---
- name: Verify sudo as admin01
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Whoami with sudo
      command: whoami
      register: whoami_result

    - debug:
        var: whoami_result.stdout