---
# List installed software as seen in the "Programs and Features" list
- name: List installed software
  hosts: all
  gather_facts: no
  tasks:
    - name: Get list of installed software from registry
      win_shell: |
        $software = Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall", "HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall" |
                    Get-ItemProperty |
                    Select-Object DisplayName, DisplayVersion, Publisher, InstallDate
        $software | ForEach-Object {
          [PSCustomObject]@{
            DisplayName     = $_.DisplayName
            DisplayVersion  = $_.DisplayVersion
            Publisher       = $_.Publisher
            InstallDate     = $_.InstallDate
          }
        } | Format-Table -AutoSize | Out-String
      register: installed_software

    - name: Show list of installed software
      debug:
        msg: "{{ installed_software.stdout }}"
