---
# List installed software as seen in the "Programs and Features" list
- name: List installed software
  hosts: all
  gather_facts: no
  tasks:
    - name: Get list of installed software from registry
      win_shell: |
        Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall", "HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall" | 
        Get-ItemProperty | 
        Select-Object DisplayName, DisplayVersion, Publisher, InstallDate
      register: installed_software

    - name: Show list of installed software
      debug:
        var: installed_software.stdout_lines
