---
# List installed software as seen in the "Programs and Features" list
- name: List installed software
  hosts: all
  gather_facts: no
  tasks:
    - name: Get list of installed software from registry
      win_shell: |
        $software = Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall", "HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall" |
                    Get-ItemProperty |
                    Select-Object DisplayName, DisplayVersion, Publisher, InstallDate
        $software | Where-Object { $_.DisplayName -ne $null } | ConvertTo-Json
      register: installed_software_json

    - name: Parse installed software JSON
      set_fact:
        installed_software_raw: "{{ installed_software_json.stdout | from_json }}"

    - name: Remove duplicate entries from installed software list
      set_fact:
        installed_software: "{{ installed_software_raw | unique(attribute='DisplayName') }}"

    - name: Show list of installed software
      debug:
        var: installed_software
