---
- name: Get Installed Updates
  hosts: windows_hosts
  gather_facts: no

  tasks:
    - name: Run PowerShell command to get installed updates
      win_shell: |
        $updates = Get-WmiObject -Class Win32_QuickFixEngineering | Select-Object -Property Description, HotFixID, InstalledOn
        $updates | ConvertTo-Json
      register: installed_updates

    - name: Print installed updates
      debug:
        var: installed_updates.stdout_lines
