---
# Automatically locate and uninstall 7-Zip if it exists
- name: Automatically locate and uninstall 7-Zip if it exists
  hosts: all
  gather_facts: no
  tasks:
    # Get list of installed software
    - name: Get list of installed software
      win_package:
        gather_subset: all
      register: installed_software

    # Find display name containing "7-Zip"
    - name: Find display name of 7-Zip
      set_fact:
        display_name: "{{ item.DisplayName }}"
      loop: "{{ installed_software.results }}"
      when: "'7-Zip' in item.DisplayName"

    # Uninstall 7-Zip if it exists
    - name: Uninstall 7-Zip if it exists
      win_package:
        name: "{{ display_name }}"
        state: absent
      when: display_name is defined
