- name: Uninstall 7-Zip
  hosts: all
  become: true
  become_method: runas
  
  tasks:
    - name: Uninstall 7-Zip
      ansible.windows.win_package:
        name: '7-Zip 23.01 (x64 edition)'
        state: absent
