---
- name: Uninstall 7-Zip if installed
  hosts: all
  gather_facts: no
  tasks:
    - name: Get list of installed software from registry
      win_shell: |
        $software = Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall", "HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall" |
                    Get-ItemProperty |
                    Select-Object DisplayName, DisplayVersion, Publisher, InstallDate, UninstallString, PSChildName
        $software | Where-Object { $_.DisplayName -ne $null } | ConvertTo-Json
      register: installed_software_json

    - name: Parse installed software JSON
      set_fact:
        installed_software_raw: "{{ installed_software_json.stdout | from_json }}"

    - name: Remove duplicate entries from installed software list
      set_fact:
        installed_software: "{{ installed_software_raw | unique(attribute='DisplayName') }}"

    - name: Find 7-Zip in the installed software list
      set_fact:
        seven_zip: "{{ installed_software | selectattr('DisplayName', 'match', '^7-Zip') | list | first }}"

    - name: Uninstall 7-Zip if it exists
      win_package:
        path: "{{ seven_zip.UninstallString if seven_zip.UninstallString.endswith('.msi') else '' }}"
        product_id: "{{ seven_zip.PSChildName if not seven_zip.UninstallString.endswith('.msi') else '' }}"
        state: absent
      when: seven_zip is defined
      register: uninstall_7zip

    - name: Reboot if uninstall required it
      win_reboot:
        when: uninstall_7zip.reboot_required

    - name: Debug output for installed software
      debug:
        var: installed_software

    - name: Debug output for found 7-Zip
      debug:
        var: seven_zip
