---
# Verify installed 7-Zip and uninstall if exists
- name: Verify installed 7-Zip and uninstall if exists
  hosts: all
  gather_facts: no
  tasks:
    # Uninstall 7-Zip if it exists
    - name: Uninstall 7-Zip if it exists
      win_package:
        name: 7-Zip  # Replace with the actual display name of 7-Zip in the "Programs and Features" list
        state: absent
