---
# Locate and uninstall 7-Zip if it exists
- name: Locate and uninstall 7-Zip if it exists
  hosts: all
  gather_facts: no
  tasks:
    # Get list of installed software
    - name: Get list of installed software
      win_package:
        fact_path: '{{ playbook_dir }}/installed_software'
        gather_facts: yes

    # Show list of installed software (for debugging purposes)
    - name: Show list of installed software
      debug:
        var: ansible_facts.installed_software

    # Uninstall 7-Zip if it exists
    - name: Uninstall 7-Zip if it exists
      win_package:
        name: "{{ item }}"
        state: absent
      loop: "{{ ansible_facts.installed_software }}"
      when: "'7-Zip' in item"
