---
- name: Manage 7-Zip on Windows hosts
  hosts: all
  gather_facts: false
  
  become: true
  become_method: runas
  become_user: "Administrator"  # Specify the user to run as
  
  tasks:
    - name: Uninstall 7-Zip
      ansible.windows.win_package:
        name: '7-Zip 23.01 (x64 edition)'
        state: absent
