---
# Automatically locate and uninstall 7-Zip if it exists
- name: Automatically locate and uninstall 7-Zip if it exists
  hosts: all
  gather_facts: no
  tasks:
    # Query the registry for 7-Zip uninstall information
    - name: Query registry for 7-Zip uninstall information
      ansible.windows.win_reg_stat:
        path: "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
      register: reg_query_result

    # Extract uninstall string for 7-Zip
    - name: Extract uninstall string for 7-Zip
      set_fact:
        uninstall_string: "{{ item.value['UninstallString'] }}"
      loop: "{{ reg_query_result.subkeys | default([]) }}"
      when: "'7-Zip' in item.value['DisplayName']"

    # Uninstall 7-Zip if uninstall string is found
    - name: Uninstall 7-Zip if uninstall string is found
      ansible.windows.win_command:
        cmd: "{{ uninstall_string }} /quiet /norestart"
      when: uninstall_string is defined
