---
# Automatically uninstall 7-Zip if it exists
- name: Automatically uninstall 7-Zip if it exists
  hosts: all
  gather_facts: no
  tasks:
    # Uninstall 7-Zip if it exists
    - name: Uninstall 7-Zip if it exists
      ansible.windows.win_command: |
        if (Test-Path "C:\\Program Files\\7-Zip\\Uninstall.exe") {
            Start-Process "C:\\Program Files\\7-Zip\\Uninstall.exe" -ArgumentList "/S" -Wait
        }
      ignore_errors: yes
