---
# Automatically locate and uninstall 7-Zip if it exists
- name: Automatically locate and uninstall 7-Zip if it exists
  hosts: all
  gather_facts: no
  tasks:
    # Query the registry for 7-Zip uninstall information
    - name: Query registry for 7-Zip uninstall information
      ansible.windows.win_shell: Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* |
                                 Where-Object {$_.DisplayName -like '*7-Zip*'} |
                                 Select-Object -ExpandProperty UninstallString
      register: uninstall_string_result

    # Uninstall 7-Zip if uninstall string is found
    - name: Uninstall 7-Zip if uninstall string is found
      ansible.windows.win_command: "{{ item }}"
      loop: "{{ uninstall_string_result.stdout_lines }}"
      when: uninstall_string_result.stdout_lines | length > 0
