---
- name: Manage 7-Zip on Windows hosts
  hosts: all
  gather_facts: false
  
  # Enable privilege escalation for the entire play
  become: true
  become_method: runas
  
  tasks:
    - name: Uninstall 7-Zip
      ansible.windows.win_package:
        name: '7-Zip 23.01 (x64 edition)'
        state: absent
