---
# Automatically locate and uninstall 7-Zip if it exists
- name: Automatically locate and uninstall 7-Zip if it exists
  hosts: all
  gather_facts: no
  tasks:
    # Get list of installed software
    - name: Get list of installed software
      win_package_facts:
        fact_path: '{{ playbook_dir }}/installed_software'
        gather_subset: all

    # Find display name containing "7-Zip"
    - name: Find display name of 7-Zip
      set_fact:
        display_name: "{{ item }}.DisplayName"
      loop: "{{ ansible_facts.win_package_facts.installed }}"
      when: "'7-Zip' in item"

    # Uninstall 7-Zip if it exists
    - name: Uninstall 7-Zip if it exists
      win_package:
        name: "{{ display_name }}"
        state: absent
      when: display_name is defined
