---
- name: Manage 7-Zip on Windows hosts
  hosts: all
  gather_facts: false
  
  become: true
  become_method: runas
  become_user: "Administrator"  # Specify the user to run as
  
  tasks:
    - name: Get 7-Zip product code from registry
      win_shell: |
        $products = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "7-Zip*" }
        if ($products) {
            Write-Output $products[0].IdentifyingNumber
        }
      register: product_code
      changed_when: false
      
    - name: Uninstall 7-Zip using MSI product code
      win_command: msiexec.exe /x "{{ product_code.stdout_lines[0] }}" /qn /norestart
      when: product_code.stdout_lines | length > 0
      register: uninstall_result
      async: 300
      poll: 5
      ignore_errors: true  # Continue even if the product is already uninstalled
