---
# Uninstall 7-Zip if it exists
- name: Uninstall 7-Zip if it exists
  hosts: all
  gather_facts: no
  tasks:
    # Get list of installed software
    - name: Get list of installed software
      win_package:
        fact_path: '{{ playbook_dir }}/installed_software'
        gather_facts: yes

    # Uninstall 7-Zip if it exists
    - name: Uninstall 7-Zip if it exists
      win_package:
        name: 7-Zip  # Replace with the actual display name of 7-Zip in the "Programs and Features" list
        state: absent
